package com.totoMauz.gameOfLife.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

import com.totoMauz.gameOfLife.control.IController;
import com.totoMauz.gameOfLife.model.Model;

/**
 * View implementation using Swing for the GUI.
 */
public class SwingView extends JFrame implements IView {
	/**
	 * Auto generated by Eclipse.
	 */
	private static final long serialVersionUID = -1538005133913482652L;
	private final JButton btnResetGame = new JButton("(Re)Start");
	private Rectangles rectangles;
	final IController controller;

	/**
	 * Initialize the Swing view and create controls.
	 * 
	 * @param controller
	 *            the controller which is triggered by controls.
	 */
	public SwingView(final IController controller) {
		super();
		this.setTitle("Game of Life");
		this.getContentPane().setLayout(null);
		this.setBounds(100, 100, 625, 575);
		addControls();
		this.setVisible(true);
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.controller = controller;
	}

	private void addControls() {
		this.btnResetGame.setBounds(500, 0, 100, 30);
		this.btnResetGame.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				SwingView.this.controller.restart();
			}
		});
		this.add(this.btnResetGame);
	}

	@Override
	public void updateView(final boolean[] data) {
		if (this.rectangles == null) {
			this.add(new Rectangles(data));
		} else {
			this.rectangles.setNewData(data);
		}
		this.revalidate();
		this.repaint();
	}

	private class Rectangles extends JPanel {
		/**
		 * Auto generated by Eclipse.
		 */
		private static final long serialVersionUID = -8352502831091810753L;
		private boolean[] cells;
		private static final int RECT_WIDTH = 10;

		public Rectangles(final boolean[] cells) {
			this.cells = cells;
			this.setBounds(0, 0, cells.length * RECT_WIDTH, cells.length * RECT_WIDTH);
		}

		public void setNewData(final boolean[] data) {
			this.cells = data;
		}

		@Override
		protected void paintComponent(final Graphics g) {
			super.paintComponent(g);

			for (int i = 0; i < this.cells.length; i++) {
				if (this.cells[i]) {
					g.setColor(Color.BLACK);
				} else {
					g.setColor(Color.WHITE);
				}
				g.fillRect((i % Model.NUM_ROWS) * RECT_WIDTH, (i / Model.NUM_COLS) * RECT_WIDTH, RECT_WIDTH, RECT_WIDTH);
			}
		}
	}
}
